# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PackUser.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='proto/PackUser.proto',
    package='com.ebanswers.starfreezer.proto',
    serialized_pb=_b(
        '\n\x14proto/PackUser.proto\x12\x1f\x63om.ebanswers.starfreezer.proto\"m\n\x08UserBody\x12\x13\n\x0buserAccount\x18\x01 \x01(\t\x12\x10\n\x08userPass\x18\x02 \x01(\t\x12\x14\n\x0cuserNickName\x18\x03 \x01(\t\x12\x0f\n\x07userSex\x18\x04 \x01(\x05\x12\x13\n\x0buserHeadUrl\x18\x05 \x01(\tB+\n\x1f\x63om.ebanswers.starfreezer.protoB\x08PackUser')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_USERBODY = _descriptor.Descriptor(
    name='UserBody',
    full_name='com.ebanswers.starfreezer.proto.UserBody',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='userAccount', full_name='com.ebanswers.starfreezer.proto.UserBody.userAccount', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='userPass', full_name='com.ebanswers.starfreezer.proto.UserBody.userPass', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='userNickName', full_name='com.ebanswers.starfreezer.proto.UserBody.userNickName', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='userSex', full_name='com.ebanswers.starfreezer.proto.UserBody.userSex', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='userHeadUrl', full_name='com.ebanswers.starfreezer.proto.UserBody.userHeadUrl', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=57,
    serialized_end=166,
)

DESCRIPTOR.message_types_by_name['UserBody'] = _USERBODY

UserBody = _reflection.GeneratedProtocolMessageType('UserBody', (_message.Message,), dict(
    DESCRIPTOR=_USERBODY,
    __module__='proto.PackUser_pb2'
    # @@protoc_insertion_point(class_scope:com.ebanswers.starfreezer.proto.UserBody)
))
_sym_db.RegisterMessage(UserBody)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
    _b('\n\037com.ebanswers.starfreezer.protoB\010PackUser'))
# @@protoc_insertion_point(module_scope)
