# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PackCustomService.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='proto/PackCustomService.proto',
    package='com.ebanswers.starfreezer.proto',
    serialized_pb=_b(
        '\n\x1dproto/PackCustomService.proto\x12\x1f\x63om.ebanswers.starfreezer.proto\"*\n\x11\x43ustomServiceBody\x12\x15\n\rserviceNumber\x18\x01 \x01(\tB4\n\x1f\x63om.ebanswers.starfreezer.protoB\x11PackCustomService')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CUSTOMSERVICEBODY = _descriptor.Descriptor(
    name='CustomServiceBody',
    full_name='com.ebanswers.starfreezer.proto.CustomServiceBody',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='serviceNumber', full_name='com.ebanswers.starfreezer.proto.CustomServiceBody.serviceNumber', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=66,
    serialized_end=108,
)

DESCRIPTOR.message_types_by_name['CustomServiceBody'] = _CUSTOMSERVICEBODY

CustomServiceBody = _reflection.GeneratedProtocolMessageType('CustomServiceBody', (_message.Message,), dict(
    DESCRIPTOR=_CUSTOMSERVICEBODY,
    __module__='proto.PackCustomService_pb2'
    # @@protoc_insertion_point(class_scope:com.ebanswers.starfreezer.proto.CustomServiceBody)
))
_sym_db.RegisterMessage(CustomServiceBody)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
    _b('\n\037com.ebanswers.starfreezer.protoB\021PackCustomService'))
# @@protoc_insertion_point(module_scope)
