// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PackRequestCmd.proto

package com.ebanswers.starfreezer.proto;

public class PackRequestCmd {
  private PackRequestCmd() {}

  /**
   * 注册命令
   */
  public static final int REGIST = 0x001;
  /**
   * 登录命令
   */
  public static final int LOGIN = 0x002;
  /**
   * 请求客服信息命令
   */
  public static final int CUSTOMER_SERVICE = 0x003;

}
