// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/PackCustomService.proto

package com.ebanswers.starfreezer.proto;

public final class PackCustomService {
  private PackCustomService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomServiceBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ebanswers.starfreezer.proto.CustomServiceBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serviceNumber = 1;</code>
     *
     * <pre>
     **
     * 客服帐号
     * </pre>
     */
    boolean hasServiceNumber();
    /**
     * <code>optional string serviceNumber = 1;</code>
     *
     * <pre>
     **
     * 客服帐号
     * </pre>
     */
    java.lang.String getServiceNumber();
    /**
     * <code>optional string serviceNumber = 1;</code>
     *
     * <pre>
     **
     * 客服帐号
     * </pre>
     */
    com.google.protobuf.ByteString
        getServiceNumberBytes();
  }
  /**
   * Protobuf type {@code com.ebanswers.starfreezer.proto.CustomServiceBody}
   */
  public static final class CustomServiceBody extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ebanswers.starfreezer.proto.CustomServiceBody)
      CustomServiceBodyOrBuilder {
    // Use CustomServiceBody.newBuilder() to construct.
    private CustomServiceBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomServiceBody(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomServiceBody defaultInstance;
    public static CustomServiceBody getDefaultInstance() {
      return defaultInstance;
    }

    public CustomServiceBody getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomServiceBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serviceNumber_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ebanswers.starfreezer.proto.PackCustomService.internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ebanswers.starfreezer.proto.PackCustomService.internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody.class, com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomServiceBody> PARSER =
        new com.google.protobuf.AbstractParser<CustomServiceBody>() {
      public CustomServiceBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomServiceBody(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomServiceBody> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVICENUMBER_FIELD_NUMBER = 1;
    private java.lang.Object serviceNumber_;
    /**
     * <code>optional string serviceNumber = 1;</code>
     *
     * <pre>
     **
     * 客服帐号
     * </pre>
     */
    public boolean hasServiceNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string serviceNumber = 1;</code>
     *
     * <pre>
     **
     * 客服帐号
     * </pre>
     */
    public java.lang.String getServiceNumber() {
      java.lang.Object ref = serviceNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serviceNumber = 1;</code>
     *
     * <pre>
     **
     * 客服帐号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServiceNumberBytes() {
      java.lang.Object ref = serviceNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serviceNumber_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNumberBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNumberBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ebanswers.starfreezer.proto.CustomServiceBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ebanswers.starfreezer.proto.CustomServiceBody)
        com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ebanswers.starfreezer.proto.PackCustomService.internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ebanswers.starfreezer.proto.PackCustomService.internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody.class, com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody.Builder.class);
      }

      // Construct using com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ebanswers.starfreezer.proto.PackCustomService.internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_descriptor;
      }

      public com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody getDefaultInstanceForType() {
        return com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody.getDefaultInstance();
      }

      public com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody build() {
        com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody buildPartial() {
        com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody result = new com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceNumber_ = serviceNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody) {
          return mergeFrom((com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody other) {
        if (other == com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody.getDefaultInstance()) return this;
        if (other.hasServiceNumber()) {
          bitField0_ |= 0x00000001;
          serviceNumber_ = other.serviceNumber_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ebanswers.starfreezer.proto.PackCustomService.CustomServiceBody) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serviceNumber_ = "";
      /**
       * <code>optional string serviceNumber = 1;</code>
       *
       * <pre>
       **
       * 客服帐号
       * </pre>
       */
      public boolean hasServiceNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string serviceNumber = 1;</code>
       *
       * <pre>
       **
       * 客服帐号
       * </pre>
       */
      public java.lang.String getServiceNumber() {
        java.lang.Object ref = serviceNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceNumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serviceNumber = 1;</code>
       *
       * <pre>
       **
       * 客服帐号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServiceNumberBytes() {
        java.lang.Object ref = serviceNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serviceNumber = 1;</code>
       *
       * <pre>
       **
       * 客服帐号
       * </pre>
       */
      public Builder setServiceNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceNumber = 1;</code>
       *
       * <pre>
       **
       * 客服帐号
       * </pre>
       */
      public Builder clearServiceNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceNumber_ = getDefaultInstance().getServiceNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceNumber = 1;</code>
       *
       * <pre>
       **
       * 客服帐号
       * </pre>
       */
      public Builder setServiceNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceNumber_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ebanswers.starfreezer.proto.CustomServiceBody)
    }

    static {
      defaultInstance = new CustomServiceBody(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ebanswers.starfreezer.proto.CustomServiceBody)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035proto/PackCustomService.proto\022\037com.eba" +
      "nswers.starfreezer.proto\"*\n\021CustomServic" +
      "eBody\022\025\n\rserviceNumber\030\001 \001(\tB4\n\037com.eban" +
      "swers.starfreezer.protoB\021PackCustomServi" +
      "ce"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ebanswers_starfreezer_proto_CustomServiceBody_descriptor,
        new java.lang.String[] { "ServiceNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
