// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/PackUser.proto

package com.ebanswers.starfreezer.proto;

public final class PackUser {
  private PackUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ebanswers.starfreezer.proto.UserBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userAccount = 1;</code>
     *
     * <pre>
     **
     * 用户帐号，目前只是手机号
     * </pre>
     */
    boolean hasUserAccount();
    /**
     * <code>optional string userAccount = 1;</code>
     *
     * <pre>
     **
     * 用户帐号，目前只是手机号
     * </pre>
     */
    java.lang.String getUserAccount();
    /**
     * <code>optional string userAccount = 1;</code>
     *
     * <pre>
     **
     * 用户帐号，目前只是手机号
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserAccountBytes();

    /**
     * <code>optional string userPass = 2;</code>
     *
     * <pre>
     **
     * 用户密码
     * </pre>
     */
    boolean hasUserPass();
    /**
     * <code>optional string userPass = 2;</code>
     *
     * <pre>
     **
     * 用户密码
     * </pre>
     */
    java.lang.String getUserPass();
    /**
     * <code>optional string userPass = 2;</code>
     *
     * <pre>
     **
     * 用户密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserPassBytes();

    /**
     * <code>optional string userNickName = 3;</code>
     *
     * <pre>
     **
     * 用户昵称
     * </pre>
     */
    boolean hasUserNickName();
    /**
     * <code>optional string userNickName = 3;</code>
     *
     * <pre>
     **
     * 用户昵称
     * </pre>
     */
    java.lang.String getUserNickName();
    /**
     * <code>optional string userNickName = 3;</code>
     *
     * <pre>
     **
     * 用户昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNickNameBytes();

    /**
     * <code>optional int32 userSex = 4;</code>
     *
     * <pre>
     **
     * 用户性别
     * </pre>
     */
    boolean hasUserSex();
    /**
     * <code>optional int32 userSex = 4;</code>
     *
     * <pre>
     **
     * 用户性别
     * </pre>
     */
    int getUserSex();

    /**
     * <code>optional string userHeadUrl = 5;</code>
     *
     * <pre>
     **
     * 用户头像
     * </pre>
     */
    boolean hasUserHeadUrl();
    /**
     * <code>optional string userHeadUrl = 5;</code>
     *
     * <pre>
     **
     * 用户头像
     * </pre>
     */
    java.lang.String getUserHeadUrl();
    /**
     * <code>optional string userHeadUrl = 5;</code>
     *
     * <pre>
     **
     * 用户头像
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserHeadUrlBytes();
  }
  /**
   * Protobuf type {@code com.ebanswers.starfreezer.proto.UserBody}
   */
  public static final class UserBody extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ebanswers.starfreezer.proto.UserBody)
      UserBodyOrBuilder {
    // Use UserBody.newBuilder() to construct.
    private UserBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserBody(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserBody defaultInstance;
    public static UserBody getDefaultInstance() {
      return defaultInstance;
    }

    public UserBody getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userAccount_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userPass_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              userNickName_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              userSex_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              userHeadUrl_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ebanswers.starfreezer.proto.PackUser.internal_static_com_ebanswers_starfreezer_proto_UserBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ebanswers.starfreezer.proto.PackUser.internal_static_com_ebanswers_starfreezer_proto_UserBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ebanswers.starfreezer.proto.PackUser.UserBody.class, com.ebanswers.starfreezer.proto.PackUser.UserBody.Builder.class);
    }

    public static com.google.protobuf.Parser<UserBody> PARSER =
        new com.google.protobuf.AbstractParser<UserBody>() {
      public UserBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserBody(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserBody> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERACCOUNT_FIELD_NUMBER = 1;
    private java.lang.Object userAccount_;
    /**
     * <code>optional string userAccount = 1;</code>
     *
     * <pre>
     **
     * 用户帐号，目前只是手机号
     * </pre>
     */
    public boolean hasUserAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string userAccount = 1;</code>
     *
     * <pre>
     **
     * 用户帐号，目前只是手机号
     * </pre>
     */
    public java.lang.String getUserAccount() {
      java.lang.Object ref = userAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAccount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userAccount = 1;</code>
     *
     * <pre>
     **
     * 用户帐号，目前只是手机号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserAccountBytes() {
      java.lang.Object ref = userAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERPASS_FIELD_NUMBER = 2;
    private java.lang.Object userPass_;
    /**
     * <code>optional string userPass = 2;</code>
     *
     * <pre>
     **
     * 用户密码
     * </pre>
     */
    public boolean hasUserPass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string userPass = 2;</code>
     *
     * <pre>
     **
     * 用户密码
     * </pre>
     */
    public java.lang.String getUserPass() {
      java.lang.Object ref = userPass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userPass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userPass = 2;</code>
     *
     * <pre>
     **
     * 用户密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserPassBytes() {
      java.lang.Object ref = userPass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNICKNAME_FIELD_NUMBER = 3;
    private java.lang.Object userNickName_;
    /**
     * <code>optional string userNickName = 3;</code>
     *
     * <pre>
     **
     * 用户昵称
     * </pre>
     */
    public boolean hasUserNickName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string userNickName = 3;</code>
     *
     * <pre>
     **
     * 用户昵称
     * </pre>
     */
    public java.lang.String getUserNickName() {
      java.lang.Object ref = userNickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userNickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userNickName = 3;</code>
     *
     * <pre>
     **
     * 用户昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNickNameBytes() {
      java.lang.Object ref = userNickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userNickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERSEX_FIELD_NUMBER = 4;
    private int userSex_;
    /**
     * <code>optional int32 userSex = 4;</code>
     *
     * <pre>
     **
     * 用户性别
     * </pre>
     */
    public boolean hasUserSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 userSex = 4;</code>
     *
     * <pre>
     **
     * 用户性别
     * </pre>
     */
    public int getUserSex() {
      return userSex_;
    }

    public static final int USERHEADURL_FIELD_NUMBER = 5;
    private java.lang.Object userHeadUrl_;
    /**
     * <code>optional string userHeadUrl = 5;</code>
     *
     * <pre>
     **
     * 用户头像
     * </pre>
     */
    public boolean hasUserHeadUrl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string userHeadUrl = 5;</code>
     *
     * <pre>
     **
     * 用户头像
     * </pre>
     */
    public java.lang.String getUserHeadUrl() {
      java.lang.Object ref = userHeadUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userHeadUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userHeadUrl = 5;</code>
     *
     * <pre>
     **
     * 用户头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserHeadUrlBytes() {
      java.lang.Object ref = userHeadUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userHeadUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userAccount_ = "";
      userPass_ = "";
      userNickName_ = "";
      userSex_ = 0;
      userHeadUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserPassBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserNickNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, userSex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUserHeadUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserPassBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserNickNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userSex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUserHeadUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ebanswers.starfreezer.proto.PackUser.UserBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ebanswers.starfreezer.proto.PackUser.UserBody prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ebanswers.starfreezer.proto.UserBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ebanswers.starfreezer.proto.UserBody)
        com.ebanswers.starfreezer.proto.PackUser.UserBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ebanswers.starfreezer.proto.PackUser.internal_static_com_ebanswers_starfreezer_proto_UserBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ebanswers.starfreezer.proto.PackUser.internal_static_com_ebanswers_starfreezer_proto_UserBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ebanswers.starfreezer.proto.PackUser.UserBody.class, com.ebanswers.starfreezer.proto.PackUser.UserBody.Builder.class);
      }

      // Construct using com.ebanswers.starfreezer.proto.PackUser.UserBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userAccount_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userPass_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userNickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        userSex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        userHeadUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ebanswers.starfreezer.proto.PackUser.internal_static_com_ebanswers_starfreezer_proto_UserBody_descriptor;
      }

      public com.ebanswers.starfreezer.proto.PackUser.UserBody getDefaultInstanceForType() {
        return com.ebanswers.starfreezer.proto.PackUser.UserBody.getDefaultInstance();
      }

      public com.ebanswers.starfreezer.proto.PackUser.UserBody build() {
        com.ebanswers.starfreezer.proto.PackUser.UserBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ebanswers.starfreezer.proto.PackUser.UserBody buildPartial() {
        com.ebanswers.starfreezer.proto.PackUser.UserBody result = new com.ebanswers.starfreezer.proto.PackUser.UserBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userAccount_ = userAccount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userPass_ = userPass_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userNickName_ = userNickName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userSex_ = userSex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userHeadUrl_ = userHeadUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ebanswers.starfreezer.proto.PackUser.UserBody) {
          return mergeFrom((com.ebanswers.starfreezer.proto.PackUser.UserBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ebanswers.starfreezer.proto.PackUser.UserBody other) {
        if (other == com.ebanswers.starfreezer.proto.PackUser.UserBody.getDefaultInstance()) return this;
        if (other.hasUserAccount()) {
          bitField0_ |= 0x00000001;
          userAccount_ = other.userAccount_;
          onChanged();
        }
        if (other.hasUserPass()) {
          bitField0_ |= 0x00000002;
          userPass_ = other.userPass_;
          onChanged();
        }
        if (other.hasUserNickName()) {
          bitField0_ |= 0x00000004;
          userNickName_ = other.userNickName_;
          onChanged();
        }
        if (other.hasUserSex()) {
          setUserSex(other.getUserSex());
        }
        if (other.hasUserHeadUrl()) {
          bitField0_ |= 0x00000010;
          userHeadUrl_ = other.userHeadUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ebanswers.starfreezer.proto.PackUser.UserBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ebanswers.starfreezer.proto.PackUser.UserBody) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userAccount_ = "";
      /**
       * <code>optional string userAccount = 1;</code>
       *
       * <pre>
       **
       * 用户帐号，目前只是手机号
       * </pre>
       */
      public boolean hasUserAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string userAccount = 1;</code>
       *
       * <pre>
       **
       * 用户帐号，目前只是手机号
       * </pre>
       */
      public java.lang.String getUserAccount() {
        java.lang.Object ref = userAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userAccount_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userAccount = 1;</code>
       *
       * <pre>
       **
       * 用户帐号，目前只是手机号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserAccountBytes() {
        java.lang.Object ref = userAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userAccount = 1;</code>
       *
       * <pre>
       **
       * 用户帐号，目前只是手机号
       * </pre>
       */
      public Builder setUserAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAccount = 1;</code>
       *
       * <pre>
       **
       * 用户帐号，目前只是手机号
       * </pre>
       */
      public Builder clearUserAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userAccount_ = getDefaultInstance().getUserAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAccount = 1;</code>
       *
       * <pre>
       **
       * 用户帐号，目前只是手机号
       * </pre>
       */
      public Builder setUserAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userAccount_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPass_ = "";
      /**
       * <code>optional string userPass = 2;</code>
       *
       * <pre>
       **
       * 用户密码
       * </pre>
       */
      public boolean hasUserPass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string userPass = 2;</code>
       *
       * <pre>
       **
       * 用户密码
       * </pre>
       */
      public java.lang.String getUserPass() {
        java.lang.Object ref = userPass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userPass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userPass = 2;</code>
       *
       * <pre>
       **
       * 用户密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserPassBytes() {
        java.lang.Object ref = userPass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userPass = 2;</code>
       *
       * <pre>
       **
       * 用户密码
       * </pre>
       */
      public Builder setUserPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userPass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userPass = 2;</code>
       *
       * <pre>
       **
       * 用户密码
       * </pre>
       */
      public Builder clearUserPass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userPass_ = getDefaultInstance().getUserPass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userPass = 2;</code>
       *
       * <pre>
       **
       * 用户密码
       * </pre>
       */
      public Builder setUserPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userPass_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userNickName_ = "";
      /**
       * <code>optional string userNickName = 3;</code>
       *
       * <pre>
       **
       * 用户昵称
       * </pre>
       */
      public boolean hasUserNickName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string userNickName = 3;</code>
       *
       * <pre>
       **
       * 用户昵称
       * </pre>
       */
      public java.lang.String getUserNickName() {
        java.lang.Object ref = userNickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userNickName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userNickName = 3;</code>
       *
       * <pre>
       **
       * 用户昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNickNameBytes() {
        java.lang.Object ref = userNickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userNickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userNickName = 3;</code>
       *
       * <pre>
       **
       * 用户昵称
       * </pre>
       */
      public Builder setUserNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userNickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userNickName = 3;</code>
       *
       * <pre>
       **
       * 用户昵称
       * </pre>
       */
      public Builder clearUserNickName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userNickName_ = getDefaultInstance().getUserNickName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userNickName = 3;</code>
       *
       * <pre>
       **
       * 用户昵称
       * </pre>
       */
      public Builder setUserNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userNickName_ = value;
        onChanged();
        return this;
      }

      private int userSex_ ;
      /**
       * <code>optional int32 userSex = 4;</code>
       *
       * <pre>
       **
       * 用户性别
       * </pre>
       */
      public boolean hasUserSex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 userSex = 4;</code>
       *
       * <pre>
       **
       * 用户性别
       * </pre>
       */
      public int getUserSex() {
        return userSex_;
      }
      /**
       * <code>optional int32 userSex = 4;</code>
       *
       * <pre>
       **
       * 用户性别
       * </pre>
       */
      public Builder setUserSex(int value) {
        bitField0_ |= 0x00000008;
        userSex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userSex = 4;</code>
       *
       * <pre>
       **
       * 用户性别
       * </pre>
       */
      public Builder clearUserSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userSex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userHeadUrl_ = "";
      /**
       * <code>optional string userHeadUrl = 5;</code>
       *
       * <pre>
       **
       * 用户头像
       * </pre>
       */
      public boolean hasUserHeadUrl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string userHeadUrl = 5;</code>
       *
       * <pre>
       **
       * 用户头像
       * </pre>
       */
      public java.lang.String getUserHeadUrl() {
        java.lang.Object ref = userHeadUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userHeadUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userHeadUrl = 5;</code>
       *
       * <pre>
       **
       * 用户头像
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserHeadUrlBytes() {
        java.lang.Object ref = userHeadUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userHeadUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userHeadUrl = 5;</code>
       *
       * <pre>
       **
       * 用户头像
       * </pre>
       */
      public Builder setUserHeadUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userHeadUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userHeadUrl = 5;</code>
       *
       * <pre>
       **
       * 用户头像
       * </pre>
       */
      public Builder clearUserHeadUrl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userHeadUrl_ = getDefaultInstance().getUserHeadUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userHeadUrl = 5;</code>
       *
       * <pre>
       **
       * 用户头像
       * </pre>
       */
      public Builder setUserHeadUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userHeadUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ebanswers.starfreezer.proto.UserBody)
    }

    static {
      defaultInstance = new UserBody(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ebanswers.starfreezer.proto.UserBody)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ebanswers_starfreezer_proto_UserBody_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ebanswers_starfreezer_proto_UserBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/PackUser.proto\022\037com.ebanswers.st" +
      "arfreezer.proto\"m\n\010UserBody\022\023\n\013userAccou" +
      "nt\030\001 \001(\t\022\020\n\010userPass\030\002 \001(\t\022\024\n\014userNickNa" +
      "me\030\003 \001(\t\022\017\n\007userSex\030\004 \001(\005\022\023\n\013userHeadUrl" +
      "\030\005 \001(\tB+\n\037com.ebanswers.starfreezer.prot" +
      "oB\010PackUser"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ebanswers_starfreezer_proto_UserBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ebanswers_starfreezer_proto_UserBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ebanswers_starfreezer_proto_UserBody_descriptor,
        new java.lang.String[] { "UserAccount", "UserPass", "UserNickName", "UserSex", "UserHeadUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
