# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PackAuth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/PackAuth.proto',
  package='com.ebanswers.starfreezer.proto',
  serialized_pb=_b('\n\x14proto/PackAuth.proto\x12\x1f\x63om.ebanswers.starfreezer.proto\"t\n\x08\x41uthBody\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nrequestCmd\x18\x02 \x01(\x05\x12\x13\n\x0bresponseCmd\x18\x03 \x01(\x05\x12\x11\n\tisSucceed\x18\x04 \x01(\x08\x12\r\n\x05pbKey\x18\x05 \x01(\t\x12\x0e\n\x06pbBody\x18\x06 \x01(\tB+\n\x1f\x63om.ebanswers.starfreezer.protoB\x08PackAuth')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AUTHBODY = _descriptor.Descriptor(
  name='AuthBody',
  full_name='com.ebanswers.starfreezer.proto.AuthBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='com.ebanswers.starfreezer.proto.AuthBody.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestCmd', full_name='com.ebanswers.starfreezer.proto.AuthBody.requestCmd', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseCmd', full_name='com.ebanswers.starfreezer.proto.AuthBody.responseCmd', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isSucceed', full_name='com.ebanswers.starfreezer.proto.AuthBody.isSucceed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pbKey', full_name='com.ebanswers.starfreezer.proto.AuthBody.pbKey', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pbBody', full_name='com.ebanswers.starfreezer.proto.AuthBody.pbBody', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['AuthBody'] = _AUTHBODY

AuthBody = _reflection.GeneratedProtocolMessageType('AuthBody', (_message.Message,), dict(
  DESCRIPTOR = _AUTHBODY,
  __module__ = 'proto.PackAuth_pb2'
  # @@protoc_insertion_point(class_scope:com.ebanswers.starfreezer.proto.AuthBody)
  ))
_sym_db.RegisterMessage(AuthBody)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037com.ebanswers.starfreezer.protoB\010PackAuth'))
# @@protoc_insertion_point(module_scope)
